name: siantri
description: SIAntri - aplikasi antrean (Flutter + Supabase)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_tts: ^4.2.0
  shared_preferences: ^2.3.0
flutter:
  uses-material-design: true
